services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: laravel-prod
    env_file: .env.prod
    depends_on:
      - postgres-prod
      - redis
    networks:
      - app_network
    command: >
      sh -c "
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        php artisan migrate --force &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - laravel
    networks:
      - app_network

  postgres-prod:
    image: postgres:17
    container_name: postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: tall_home_budget
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis-prod
    networks:
      - app_network

networks:
  app_network:

volumes:
  pg_data_prod:
