services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: laravel-preprod
    env_file: .env.preprod
    depends_on:
      - postgres-preprod
      - redis
    networks:
      - app_network
    command: >
      sh -c "
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        php artisan migrate --force &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: nginx-preprod
    volumes:
      - ./nginx.preprod.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - laravel
    networks:
      - app_network

  postgres-preprod:
    image: postgres:17
    container_name: postgres-preprod
    restart: unless-stopped
    environment:
      POSTGRES_DB: tall_home_budget_preprod
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data_preprod:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis-preprod
    networks:
      - app_network

networks:
  app_network:

volumes:
  pg_data_preprod:
