services:
  app:
    image: ghcr.io/titerin/home-budget-build:latest
    container_name: home-budget
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - storage:/var/www/html/storage
      - app-public:/var/www/html/public
    depends_on:
      - postgres

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8010:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - storage:/var/www/html/storage:ro
      - app-public:/var/www/html/public:ro
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d app" ]
      interval: 5s
      timeout: 3s
      retries: 20


  init-public:
    image: ghcr.io/titerin/home-budget-build:latest
    container_name: home-budget-init-public
    restart: "no"
    volumes:
      - app-public:/target-public
    entrypoint: [ "/bin/sh", "-lc" ]
    command: >
      echo "Hydrating public volume (app-public)â€¦" &&
      rm -rf /target-public/* &&
      cp -a /var/www/html/public/. /target-public/ &&
      echo "Done."

  migrate:
    image: ghcr.io/titerin/home-budget-build:latest
    container_name: home-budget-migrate
    restart: "no"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-lc" ]
    command: >
      php artisan migrate --force


volumes:
  storage:
  postgres-data:
  app-public:
